# Generated by Django 2.1 on 2018-08-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0003_auto_20180821_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='taken_by',
        ),
    ]
