# Generated by Django 2.1 on 2018-08-21 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0004_remove_job_taken_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='taken_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cantake_jobs', to='log_in.User'),
        ),
    ]
